packages:
  - packages/*

minimumReleaseAge: 2880

catalogMode: prefer

catalog:
  '@types/node': ^25.6.0
  typescript: ^6.0.0
  vite-plus: ^0.1.18
  vitest: ^4.1.4

allowBuilds:
  protobufjs: true

onlyBuiltDependencies:
  - protobufjs
