packages:
  - packages/*

minimumReleaseAge: 2880

catalogMode: prefer

catalog:
  '@types/node': ^25.6.0
  typescript: ^7.0.0
  vite-plus: ^0.3.0
  vitest: ^5.0.0

allowBuilds:
  protobufjs: true

onlyBuiltDependencies:
  - protobufjs
